name : build + eslint

# 이벤트를 발생시킬 트리거
on:
	pull_request: 
		branches:
			- develop 
jobs:
	check:
		name: check 
		runs-on: ubuntu-latest
		steps:
		  - uses: actions/checkout@v3 
		  - name: Install client dependencies 
			  run : |
          cd client
          npm install 
		  - name: Install server dependencies 
			  run : |
          cd server
          npm install

		  - name: Check eslint
        run : |
          ./client/node_modules/.bin/eslint client/src --ext .js,.jsx
          ./client/node_modules/.bin/eslint server --ext .js,.jsx

		  - name: Run build check # 빌드 돌리기
        run: |
          cd client
          npm run build
